### ISSUE TITLE
JsFormat not working on Sublime 3 since few days ago

### ISSUE THREAD

**Issue by yorch** [jdavisclark/JsFormat#170] opened 2016-04-21 16:04 UTC
Hello,

Thanks for the plugin, really helpful.

Since few days ago, it has stopped working for me, it used to work fine but now I'm getting the following error in the console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "js_formatter in /Users/yorch/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package", line 88, in run
  File "/Users/yorch/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/src/jsf.py", line 79, in format_whole_file
  File "/Users/yorch/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 234, in beautify
  File "/Users/yorch/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 383, in beautify
  File "/Users/yorch/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 1349, in __init__
  File "/Users/yorch/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 154, in __init__
zipimport.ZipImportError: bad local file header in /Users/yorch/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package
```

I've tried uninstalling and installing the package again but no luck.

Any clues?

Thanks

**Comment by jdc0589** [comment] 2016-04-21 17:24
@yorch this is a bug with package control or github, I can't remember which; the zip archive is corrupted.

Try removing JsFormat, closing sublime (completely), and reinstalling.
If that doesn't work, try a manual install without package control (just realize you won't get updates automatically)

**Comment by wbond** [comment] 2016-04-21 17:37
This is most likely caused by https://github.com/jdc0589/JsFormat/blob/master/js_formatter.py#L30. `zipimport` caches the file handle to do reloads. I don't believe this really has anything to do with Sublime's `ZipImport` or Package Control. You may notice it with Package Control when hot-reloads happen during upgrade, but that is because you aren't removing your custom `sys.path` entries (and `sys.modules` entries) when the package is unloaded.

Most likely you should refactor JsFormat to use relative imports with Python 3 instead of messing with `sys.path`.

**Comment by jdc0589** [comment] 2016-04-21 21:26
@wbond. Thanks. Most of that was in there from the pre-ST3 days. I honestly don't know what kind of ST2 userbase is still even around.

**Comment by tufandevrim** [comment] 2016-04-22 09:05
Same issue on selection as well
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "js_formatter in /Users/dtufan/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package", line 86, in run
  File "/Users/dtufan/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/src/jsf.py", line 53, in format_selection
  File "/Users/dtufan/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 234, in beautify
  File "/Users/dtufan/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 383, in beautify
  File "/Users/dtufan/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 1349, in __init__
  File "/Users/dtufan/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs/jsbeautifier/jsbeautifier/__init__.py", line 154, in __init__
zipimport.ZipImportError: bad local file header in /Users/dtufan/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package
```

**Comment by jdc0589** [comment] 2017-01-04 19:36
@patik I think what you are experiencing is a different issue. That looks like Package Control territory.

**Comment by wbond** [comment] 2017-01-04 19:39
@patik If the domain didn't resolve, you wouldn't get a 403. I can download that URL without issue, so it is likely something else.

I would start with https://packagecontrol.io/docs/troubleshooting#Purging_and_Reinstalling and then try https://packagecontrol.io/docs/troubleshooting#Enabling_the_Debug_Log.

If you continue to have issues, and you think it is an issue with Package Control, open an issue at https://github.com/wbond/package_control/issues/new.

**Comment by jdc0589** [comment] 2017-01-04 19:41
@patik I missed the bit about it being a 403. But for the record, I also could not hit that url when you originally commented. It seems to work fine now though.

**Comment by onlynight** [comment] 2018-06-25 09:16
i have same problem too, how can i fix it, thanks.

```
Package Control: Error downloading package.
HTTP error 404 downloading https://codeload.github.com/jdc0589/JsFormat/zip/master.
```

**Comment by bitwiseman** [comment] 2019-01-20 01:39
It looks like this was fixed.

**Closed by bitwiseman** 2019-01-20 01:39 UTC
